site_name: Manual do Portal Serratec
site_url: https://portalserratec.netlify.app/
site_author: Time de Desenvolvedores Serratec.
site_description: Documentação completa do Portal do Candidato, incluindo guia do Usuário e manuais para Desenvolvedores e Gestores.

repo_url: https://github.com/RTIC-STEM/2024_2_Serratec_Portal_do_Candidato
repo_name: RTIC-STEM/2024_2_Serratec_Portal_do_Candidato
repo_type: github
copyright: '© 2024 RTIC-STEM. Todos os direitos reservados.'
repo_branch: main

# Ativa o diretório de customização
custom_dir: overrides

theme:
  name: material
  language: pt
  # Paleta de Cores com Alternador
  palette:
    # Paleta para modo claro
    - scheme: default
      primary: '#2D81C3'
      accent: '#2D81C3'
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Paleta para modo escuro
    - scheme: slate
      primary: '#2D81C3'
      accent: '#2D81C3'
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - -navigation.instant # Mantemos isso desativado por segurança

# Carrega os nossos ficheiros de customização
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/font-sizer.js

plugins:
  - search
  - encryptcontent

nav:
  - 'Início': 'index.md'
  - 'Manual do Candidato':
    - 'Etapa 1: Criando a Conta': '1-criando-a-conta.md'
    - 'Etapa 2: Primeiro Acesso': '2-primeiro-acesso.md'
    - 'Etapa 3: Preenchendo o Perfil': '3-preenchendo-o-perfil.md'
    - 'Etapa 4: Inscrição no Programa': '4-inscricao.md'
    - 'Etapa 5: Acompanhamento': '5-acompanhamento.md'
  - 'Manual do Gestor':
    - 'Visão Geral e Acesso': 'gestor/00-inicio.md'
    - '1. Gestão de Regiões': 'gestor/01-regioes.md'
    - '2. Criando um Processo Seletivo': 'gestor/02-criando-processo.md'
    - '3. Gerenciando Etapas e Avaliações': 'gestor/03-etapas-e-avaliacoes.md'
    - '4. Gerenciando Resultados': 'gestor/04-gerenciando-resultados.md'
    - '5. Acompanhamento Final': 'gestor/05-acompanhamento-final.md'
  - 'Manual do Desenvolvedor':
    - 'Introdução e Visão Geral': 'desenvolvedor/00-introducao.md'
    - 'Arquitetura e Tecnologias': 'desenvolvedor/01-arquitetura.md'
    - 'Ambiente Local (Docker)': 'desenvolvedor/02-ambiente-local.md'
    - 'API e Endpoints (Swagger)': 'desenvolvedor/03-api-e-endpoints.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences